name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application Jar
      working-directory: ./backend-api/rest-with-springboot-erudio
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./backend-api
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_erudio:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_erudio:latest
